[package]
name = "hmm"
version = "0.1.0"
authors = ["Bourgond Aries <macocio@gmail.com>"]

[dependencies]
clippy = "0.0.58"
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
env_logger = "0.3.3"
fps_counter = "0.2.0"
log = "0.3.5"
rand = "0.3.14"
sfml = "0.11.2"
time = "0.1.34"
toml = "0.1.28"
